version: '3.2'

services:
  postgres:
    image: postgres:10.5
    volumes:
      - './db_data:/var/lib/postgresql/data:delegated'
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - '5672:5672'

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A drag_race_predictions worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - rabbitmq
